title: Python Tools for Visual Studio
description: Free, open source plugin that turns Visual Studio into a Python IDE
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions
